### PR TITLE
Added EthernetClient.remoteIP() to return the IPAddress of the remote machine

### PR DESCRIPTION
**Pull request by 0neblock**
The ESP8266 Arduino core has the functionality to remoteIP() on the Client interface to get the address of the connected TCP client, and I thought it would be useful to expose a similar function in the EthernetClass.

This works both in client and server mode, which can be convenient if you are running a web server and want to know the IP of the client who has connected.

Let me know of any comments or Questions.

Thanks.

### CODE REVIEW

**Comment by greyltc** [comment]
I'd love to see this merged!

**Review by per1234 — CHANGES_REQUESTED** [review]
The last two commits are unrelated to the stated purpose of this PR:
- https://github.com/adafruit/Ethernet2/pull/20/commits/5bf72c6c88668129219ef93bf4e339ae80a2549c
- https://github.com/adafruit/Ethernet2/pull/20/commits/082c148e764558d30cbea065be50eb62414d5018

Maybe they were pushed accidentally to this branch?

**Comment by 0neblock** [comment]
@per1234 you were right, sorry, I've reverted that. Thanks for pointing it out!

**Comment by tshikaboom** [comment]
Humbly bumping this, would also like to see this merged; currently i'm locally patching the library.

Cheers!

**Comment by ladyada** [comment]
hey Oneblock, have you tested this on an AVR or SAMD (chip other than ESP8266?)

**Comment by tshikaboom** [comment]
FWIW this works fine on a SAMD21 chip which I use at the moment.

**Comment by per1234** [comment]
This functionality was added to the official Arduino Ethernet library in the 2.0.0 release:
- https://github.com/arduino-libraries/Ethernet/blob/master/src/Ethernet.h#L239
- https://github.com/arduino-libraries/Ethernet/blob/master/src/EthernetClient.cpp#L191-L201

**Comment by ladyada** [comment]
oooh i didn't see that the official library was revived! well, we'd really prefer to not maintain a fork - can both of y'all try the arduino library, does that work for you? we could then archive this one :)

**Comment by tshikaboom** [comment]
So I've tried the official Ethernet library and it seems to be working well for what I use it (including this functionality).
Cheers and a happy new year!

**Comment by ladyada** [comment]
yep verified, works great - going to archive this library

**Pull request closed without merging**
