### PR TITLE
Define the settings for the SPI transaction

### PR DESCRIPTION
**Pull request by gopimn**
Added the definition of the settings

### CODE REVIEW

**Comment by ladyada** [comment]
hey last night i added SPI transactions so i believe this pull request is, essentially, already done?

**Comment by gopimn** [comment]
changes where'nt reflected on the master branch.

**Comment by ladyada** [comment]
https://github.com/adafruit/Ethernet2/blob/master/src/utility/w5500.cpp#L105
?

**Comment by gopimn** [comment]
everything is clear now thaks!

**Pull request closed without merging**
